### PR TITLE
chore: add xhr2 package

### PR DESCRIPTION
**Pull request by im-adithya**
This should fix the error described in https://github.com/haveno-dex/haveno/issues/1482.

To use:
`npm install`
`npm pack`

and install the packaged file in sample app
`npm install haveno-ts-0.0.30.tgz`
`npm run start`

You will not see the `XMLHttpRequest is not defined` error anymore

### CODE REVIEW

**Comment by im-adithya** [comment]
@woodser please review :)

**Review by bl4ck-cod3 — COMMENTED** [review]
All this does is override the XMLHttpRequest object that is being used with a global object.  this introduces multiple other issues and does not solve the initial problem of XMLHttpRequest being called in specific places and being undefined.  Furthermore global variables create a maintenance nightmare.

**Comment by im-adithya** [comment]
@woodser I thought it would be good to bundle xhr2 along so it comes with `haveno-ts`, let me know if you have any concerns about `XMLHttpRequest` being a global object

**Comment by woodser** [comment]
Moved to https://github.com/haveno-dex/haveno-ts/pull/339

**Pull request closed without merging**
